## Remote package repositories
src/gz openwrt_core https://downloads.openwrt.org/releases/24.10.4/targets/ath79/generic/packages
src/gz openwrt_base https://downloads.openwrt.org/releases/24.10.4/packages/mips_24kc/base
src/gz openwrt_kmods https://downloads.openwrt.org/releases/24.10.4/targets/ath79/generic/kmods/6.6.110-1-35ef4dd36891d37023436baa842fa311
src/gz openwrt_luci https://downloads.openwrt.org/releases/24.10.4/packages/mips_24kc/luci
src/gz openwrt_packages https://downloads.openwrt.org/releases/24.10.4/packages/mips_24kc/packages
src/gz openwrt_routing https://downloads.openwrt.org/releases/24.10.4/packages/mips_24kc/routing
src/gz openwrt_telephony https://downloads.openwrt.org/releases/24.10.4/packages/mips_24kc/telephony

## This is the local package repository, do not remove!
src imagebuilder file:packages

option check_signature
